team: team
pipeline: update-pipeline-and-tag
platform: actions

feature_toggles:
- update-pipeline-and-tag
- update-actions

tasks:
- type: parallel
  tasks:
  - type: docker-compose
    name: A1
  - type: docker-compose
    name: A2
- type: docker-compose
  name: B
